version: 0.2

env:
  variables: FUNCTION_NAME="cicd-demo"
    ZIP_FILE=lambda.zip
#     JAVA_HOME: '/usr/lib/jvm/java-8-openjdk-amd64'
#   parameter-store:
#     LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    runtime-versions:
      nodejs: 24.x
    commands:
      - yum install zip -y
      - aws lambda update-function-code \
        --function-name  $FUNCTION_NAME \
        --zip-file fileb://$ZIP_FILE
  build:
    commands:
      - echo prepared ZIP...
      - zip -r $ZIP_FILE .
      - echo deploy lambda function $FUNCTION_NAME
